# Generated by Django 5.1.5 on 2025-01-31 19:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_categoria', models.CharField(default='', max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Categorias',
            },
        ),
        migrations.CreateModel(
            name='Cidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_cidade', models.CharField(default='', max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Cidades',
            },
        ),
        migrations.CreateModel(
            name='Colaborador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_colaborador', models.CharField(default='', max_length=100)),
                ('email', models.EmailField(default='', max_length=50)),
                ('telefone', models.CharField(default='', max_length=13)),
                ('cargo', models.CharField(default='', max_length=50)),
            ],
            options={
                'verbose_name_plural': 'Colaboradores',
            },
        ),
        migrations.CreateModel(
            name='Local',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_local', models.CharField(default='', max_length=100)),
                ('capacidade', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'Locais',
            },
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_material', models.CharField(default='', max_length=100)),
                ('qtd', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'Materiais',
            },
        ),
        migrations.CreateModel(
            name='MeioDivulgacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meio_divulgacao', models.CharField(default='', max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Meios de Divulgação',
            },
        ),
        migrations.CreateModel(
            name='Organizador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_organizador', models.CharField(default='', max_length=100)),
                ('instituicao', models.CharField(default='', max_length=100)),
                ('email', models.EmailField(default='', max_length=50)),
                ('telefone', models.CharField(default='', max_length=13)),
            ],
            options={
                'verbose_name_plural': 'Organizadores',
            },
        ),
        migrations.CreateModel(
            name='Parceria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_parceiro', models.CharField(default='', max_length=100)),
                ('descricao', models.CharField(default='', max_length=150)),
            ],
            options={
                'verbose_name_plural': 'Parcerias',
            },
        ),
        migrations.CreateModel(
            name='Publico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('publico', models.CharField(default='', max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Públicos',
            },
        ),
        migrations.CreateModel(
            name='TipoCobertura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_cobertura', models.CharField(default='', max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Tipos de Cobertura',
            },
        ),
        migrations.CreateModel(
            name='TipoParceria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_parceria', models.CharField(default='', max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Tipos de Parceria',
            },
        ),
        migrations.CreateModel(
            name='UF',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uf', models.CharField(default='', max_length=2)),
            ],
            options={
                'verbose_name_plural': 'UFs',
            },
        ),
        migrations.CreateModel(
            name='Cobertura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cobertura_colaborador', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='app.colaborador')),
                ('tipo_cobertura', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='app.tipocobertura')),
            ],
            options={
                'verbose_name_plural': 'Coberturas',
            },
        ),
        migrations.CreateModel(
            name='Divulgacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('divulgacao', models.CharField(default='', max_length=100)),
                ('cobertura', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='app.cobertura')),
            ],
            options={
                'verbose_name_plural': 'Divulgações',
            },
        ),
        migrations.CreateModel(
            name='Instituicao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_instituicao', models.CharField(default='', max_length=100)),
                ('cidade', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='app.cidade')),
            ],
            options={
                'verbose_name_plural': 'instituições',
            },
        ),
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_evento', models.CharField(default='', max_length=100)),
                ('data_evento', models.DateField(default='2000-01-01')),
                ('horario_inicio', models.TimeField(default='00:00:00')),
                ('horario_fim', models.TimeField(default='00:00:00')),
                ('descricao', models.CharField(default='', max_length=150)),
                ('qtd_publico', models.IntegerField(default=0)),
                ('categoria', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='app.categoria')),
                ('cobertura', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='app.cobertura')),
                ('local', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='app.local')),
                ('material', models.ManyToManyField(default='', to='app.material')),
                ('organizador', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='app.organizador')),
                ('parceria', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='app.parceria')),
                ('publico', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='app.publico')),
            ],
            options={
                'verbose_name_plural': 'Eventos',
            },
        ),
        migrations.AddField(
            model_name='parceria',
            name='tipo_parceria',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='app.tipoparceria'),
        ),
        migrations.AddField(
            model_name='cidade',
            name='uf',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='app.uf'),
        ),
    ]
