# Generated by Django 5.1.5 on 2025-01-28 16:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_categoria', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Categorias',
            },
        ),
        migrations.CreateModel(
            name='Cobertura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_colaborador', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=50)),
                ('telefone', models.CharField(max_length=13)),
                ('cargo', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name_plural': 'Coberturas',
            },
        ),
        migrations.CreateModel(
            name='Local',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_local', models.CharField(max_length=100)),
                ('capacidade', models.IntegerField()),
            ],
            options={
                'verbose_name_plural': 'Locais',
            },
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_material', models.CharField(max_length=100)),
                ('qtd', models.IntegerField()),
            ],
            options={
                'verbose_name_plural': 'Materiais',
            },
        ),
        migrations.CreateModel(
            name='MeioDivulgacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meio_divulgacao', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Meios de Divulgação',
            },
        ),
        migrations.CreateModel(
            name='Organizador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_organizador', models.CharField(max_length=100)),
                ('instituicao', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=50)),
                ('telefone', models.CharField(max_length=13)),
            ],
            options={
                'verbose_name_plural': 'Organizadores',
            },
        ),
        migrations.CreateModel(
            name='Parceria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_parceiro', models.CharField(max_length=100)),
                ('tipo_parceria', models.CharField(max_length=100)),
                ('descricao', models.CharField(max_length=150)),
            ],
            options={
                'verbose_name_plural': 'Parcerias',
            },
        ),
        migrations.CreateModel(
            name='Publico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('publico', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Públicos',
            },
        ),
        migrations.CreateModel(
            name='TipoDivulgacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_divulgacao', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Tipos de Divulgação',
            },
        ),
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_evento', models.CharField(max_length=100)),
                ('data_evento', models.DateField()),
                ('horario_inicio', models.TimeField()),
                ('horario_fim', models.TimeField()),
                ('descricao', models.CharField(max_length=150)),
                ('qtd_publico', models.IntegerField()),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.categoria')),
                ('cobertura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.cobertura')),
                ('local', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.local')),
                ('material', models.ManyToManyField(to='app.material')),
                ('organizador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.organizador')),
                ('parceria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.parceria')),
                ('publico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.publico')),
            ],
            options={
                'verbose_name_plural': 'Eventos',
            },
        ),
    ]
