# Generated by Django 5.1.5 on 2025-02-03 18:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organizador',
            name='instituicao',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='app.instituicao'),
        ),
    ]
