# Generated by Django 5.1.5 on 2025-01-28 19:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_cidade_options_alter_uf_options_instituicao'),
    ]

    operations = [
        migrations.CreateModel(
            name='Colaborador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_colaborador', models.CharField(default='', max_length=100)),
                ('email', models.EmailField(default='', max_length=50)),
                ('telefone', models.CharField(default='', max_length=13)),
                ('cargo', models.CharField(default='', max_length=50)),
            ],
            options={
                'verbose_name_plural': 'Colaboradores',
            },
        ),
        migrations.CreateModel(
            name='TipoCobertura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_cobertura', models.CharField(default='', max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Tipos de Cobertura',
            },
        ),
        migrations.RemoveField(
            model_name='cobertura',
            name='cargo',
        ),
        migrations.RemoveField(
            model_name='cobertura',
            name='email',
        ),
        migrations.RemoveField(
            model_name='cobertura',
            name='nome_colaborador',
        ),
        migrations.RemoveField(
            model_name='cobertura',
            name='telefone',
        ),
        migrations.AlterField(
            model_name='categoria',
            name='nome_categoria',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='cidade',
            name='nome_cidade',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='cidade',
            name='uf',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='app.uf'),
        ),
        migrations.AlterField(
            model_name='evento',
            name='categoria',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='app.categoria'),
        ),
        migrations.AlterField(
            model_name='evento',
            name='cobertura',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='app.cobertura'),
        ),
        migrations.AlterField(
            model_name='evento',
            name='data_evento',
            field=models.DateField(default='2000-01-01'),
        ),
        migrations.AlterField(
            model_name='evento',
            name='descricao',
            field=models.CharField(default='', max_length=150),
        ),
        migrations.AlterField(
            model_name='evento',
            name='horario_fim',
            field=models.TimeField(default='00:00:00'),
        ),
        migrations.AlterField(
            model_name='evento',
            name='horario_inicio',
            field=models.TimeField(default='00:00:00'),
        ),
        migrations.AlterField(
            model_name='evento',
            name='local',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='app.local'),
        ),
        migrations.AlterField(
            model_name='evento',
            name='material',
            field=models.ManyToManyField(default='', to='app.material'),
        ),
        migrations.AlterField(
            model_name='evento',
            name='nome_evento',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='evento',
            name='organizador',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='app.organizador'),
        ),
        migrations.AlterField(
            model_name='evento',
            name='parceria',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='app.parceria'),
        ),
        migrations.AlterField(
            model_name='evento',
            name='publico',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='app.publico'),
        ),
        migrations.AlterField(
            model_name='evento',
            name='qtd_publico',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='instituicao',
            name='cidade',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='app.cidade'),
        ),
        migrations.AlterField(
            model_name='instituicao',
            name='nome_instituicao',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='local',
            name='capacidade',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='local',
            name='nome_local',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='material',
            name='nome_material',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='material',
            name='qtd',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='meiodivulgacao',
            name='meio_divulgacao',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='organizador',
            name='email',
            field=models.EmailField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='organizador',
            name='instituicao',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='organizador',
            name='nome_organizador',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='organizador',
            name='telefone',
            field=models.CharField(default='', max_length=13),
        ),
        migrations.AlterField(
            model_name='parceria',
            name='descricao',
            field=models.CharField(default='', max_length=150),
        ),
        migrations.AlterField(
            model_name='parceria',
            name='nome_parceiro',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='parceria',
            name='tipo_parceria',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='publico',
            name='publico',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='tipodivulgacao',
            name='tipo_divulgacao',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='uf',
            name='uf',
            field=models.CharField(default='', max_length=2),
        ),
        migrations.AddField(
            model_name='cobertura',
            name='cobertura_colaborador',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='app.colaborador'),
        ),
        migrations.CreateModel(
            name='Divulgacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('divulgacao', models.CharField(default='', max_length=100)),
                ('cobertura', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='app.cobertura')),
            ],
            options={
                'verbose_name_plural': 'Divulgações',
            },
        ),
        migrations.AddField(
            model_name='cobertura',
            name='tipo_cobertura',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='app.tipocobertura'),
        ),
    ]
