# Generated by Django 5.1.5 on 2025-01-28 19:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_colaborador_tipocobertura_remove_cobertura_cargo_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TipoDivulgacao',
        ),
    ]
