# Generated by Django 5.1.5 on 2025-01-28 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_delete_tipodivulgacao'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoParceria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_parceria', models.CharField(default='', max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Tipos de Parceria',
            },
        ),
    ]
